# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: chat.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 5, 27, 2, "", "chat.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\nchat.proto"\x07\n\x05\x45mpty"(\n\x04User\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x0e\n\x06online\x18\x02 \x01(\x08" \n\x08UserList\x12\x14\n\x05users\x18\x01 \x03(\x0b\x32\x05.User"@\n\x0b\x43hatMessage\x12\x0e\n\x06sender\x18\x01 \x01(\t\x12\x10\n\x08receiver\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t"\x16\n\x03\x41\x63k\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32U\n\x0b\x43hatService\x12#\n\x0eGetOnlineUsers\x12\x06.Empty\x1a\t.UserList\x12!\n\x0bSendMessage\x12\x0c.ChatMessage\x1a\x04.Ackb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "chat_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_EMPTY"]._serialized_start = 14
    _globals["_EMPTY"]._serialized_end = 21
    _globals["_USER"]._serialized_start = 23
    _globals["_USER"]._serialized_end = 63
    _globals["_USERLIST"]._serialized_start = 65
    _globals["_USERLIST"]._serialized_end = 97
    _globals["_CHATMESSAGE"]._serialized_start = 99
    _globals["_CHATMESSAGE"]._serialized_end = 163
    _globals["_ACK"]._serialized_start = 165
    _globals["_ACK"]._serialized_end = 187
    _globals["_CHATSERVICE"]._serialized_start = 189
    _globals["_CHATSERVICE"]._serialized_end = 274
# @@protoc_insertion_point(module_scope)
